### ISSUE TITLE
Question: How to implement this to enable link to redirect to discourse with current logged in user

### ISSUE THREAD

**Issue by tandasima** [jaewun/discourse-sso-laravel#2]
Hi there, thank you for this. Looking good.

Question.

Lets say there is a link to discourse, I want that when I click that link, it takes me to discourse with the current logged in user already logged in to discourse too. How would I implement this to login the current logged in user directly to discourse without getting an error?

I tried to use your route code in the Http folder  but I get something went wrong message and no log info.

Thank you.

**Comment by tandasima** [comment]
I managed to fix it. I noticed I didnt put the http in my sso url string in discourse setting.

Thanks again.

**Comment by jaewun** [comment]
You can also send the user to this (on your discourse instance), set return_path to the intended destination. IE if you want to log someone in and send them to categories automatically send them to this...

`http://discourse.example.com/session/sso?return_path=/categories`

It will start the single-sign on flow and send them to the given URL once authenticated.

**Comment by tandasima** [comment]
awesome! thanks for letting me know about that.

kudos!
